# Build settings
gems:
  - jekyll-paginate

# Site settings
title: "symbols under the dresser"
description: > # this means to ignore newlines until "email:"
   Writeups and notes on security and other content

email: thundr@protonmail.ch
#blog logo
logo: "/assets/images/favicon.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/line_noise_1.png"

name: 'thundR'
author: 'thundR'
author_image: "/assets/images/favicon.png"

paginate:	5

url: "http://thundr.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/thundR
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
  - icon: ello
    url:  https://ello.co/thundr
    desc: Ello
    share_url:
    share_title:
    share_link: